version: '3.8'
 
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    #restart: unless-stopped