apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dorian-nextjs
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust as necessary