apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dorian-nextjs
  name: dorian-nextjs-app
  labels:
    app: dorian-nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dorian-nextjs-app
  template:
    metadata:
      labels:
        app: dorian-nextjs-app
    spec:
      containers:
      - name: dorian-nextjs-container
        image: doriancottle/dorian-nextjs:${IMAGE_TAG}  
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          value: dorian-db-svc
        - name: POSTGRES_USER
          value: test-user
        - name: POSTGRES_PASSWORD
          value: test-password
        - name: POSTGRES_DB
          value: db
        - name: NEXT_PUBLIC_REDIRECT_URI
          value: https://dorjs.duckdns.org/
 
