apiVersion: v1
kind: Service
metadata:
 name: dorian-nextjs-app-svc
 namespace: dorian-nextjs
spec: 
  type: ClusterIP
  selector:
    app: dorian-nextjs-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP