import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavLinks from "./nav-links";
import Providers from "../../features/authentication/providers";
import { getUserFromCookie } from "../../features/authentication/getUserFromCookie";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//lookup jose npm docs



//emails are a good unique identifier
//also keycloak id

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromCookie(); //use this to get logged in user information on any page.tsx
  
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header>
            <div>
              {user ? user.givenName : ""}
              <NavLinks />
              {children}
            </div>
          </header>
        </body>
      </Providers>
    </html>
  );
}
